/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mvc.visao;

import com.mvc.modelos.ClientesBean;
import com.mvc.controle.Controle;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul
 */
public class VisualizacaoClientes extends javax.swing.JFrame {

    private static Controle controle = new Controle();
    private static List<ClientesBean> listaDeCadastros;

    /**
     * Creates new form VisualizacaoClientes
     */
    public VisualizacaoClientes() {
        initComponents();
        
        try {
            
            //aqui vou carregar dos dados na tela
            //listaDeCadastros = controle.listarClientes();
            listaDeCadastros = controle.tabelaClientes();

            atualizarTabelaItem(listaDeCadastros);

            //------------------------
            // constrói a primeira data
            DateFormat fm = new SimpleDateFormat(
                    "dd/MM/yyyy HH:mm:ss");
            Date data1 = (Date) fm.parse("01/05/2015 11:59:59");

            // constrói a segunda data
            fm = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data2 = (Date) fm.parse("02/05/2015 11:59:59");

            // vamos obter a diferença em semanas, dias, horas,
            // minutos e segundos
            long segundos = (data2.getTime() - data1.getTime()) / 1000;
            int semanas = (int) Math.floor(segundos / 604800);
            segundos -= semanas * 604800;
            int dias = (int) Math.floor(segundos / 86400);
            segundos -= dias * 86400;
            int horas = (int) Math.floor(segundos / 3600);
            segundos -= horas * 3600;
            int minutos = (int) Math.floor(segundos / 60);
            segundos -= minutos * 60;

            // exibe o resultado
            System.out.println("As duas datas tem "
                    + semanas + " semanas, " + dias + " dias, "
                    + horas + " horas, " + minutos + " minutos e "
                    + segundos + " segundos de diferença");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Novo");

        jButton2.setText("Apagar");

        jLabel1.setText("Para alterar duplo click no registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            selecionar();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizacaoClientes().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    //==============================================================
    void atualizarTabelaItem(List<ClientesBean> listaAuxiliarBean) {

        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        if (listaAuxiliarBean != null && listaAuxiliarBean.size() > 0) {

            for (ClientesBean o : listaAuxiliarBean) {
                Object[] linha = {
                    o.getId(),
                    o.getNome(),};

                ((DefaultTableModel) jTable1.getModel()).addRow(linha);
            }

            jTable1.setRowSelectionInterval(0, 0); //da pau quando vazia
            jTable1.requestFocus();
        }

    }

    private void selecionar() {

        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!!!");
            return;
        }

        ClientesBean aux = listaDeCadastros.get(linhaSelecionada);
        CadastroClientes cadastroClientes = new CadastroClientes(this, true);
        cadastroClientes.setClienteSelecionado(aux);
        cadastroClientes.setVisible(true);

    }
}
